[package]
name = "starbeam"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.18.0", features = ["file_watcher"] }
noise = "0.9"
serde = { version = "1", features = ["derive"] }
ron = "0.10"
thiserror = "2"
bevy_egui = "0.39"
rand = "0.8"
